CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Human                         MNPSAPSYPMASLYVGDLHPDVTEAMLYEKFSPAGPILSIRVCRDMITRRSLGYAYVNFQ
Honeycomb-rockfish            MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Pinecone-soldierfish          MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Channel-bull-blenny           MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Three-spined-stickleback      MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Ninespine-stickleback         MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Wolf-eel                      MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Tanaka's-snailfish            MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
Lumpsucker                    MNPSAPSYPMASLYVGDLHQDVTEAMLYEKFSPAGAILSIRVCRDMITRRSLGYAYVNFQ
                              ******************* ***************.************************

Human                         QPADAERALDTMNFDVIKGKPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Honeycomb-rockfish            QPADAERALDTMNFDVIKGRPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Pinecone-soldierfish          QPADAERALDTMNFDVIKGRPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Channel-bull-blenny           QPPDAERALDTMNFDVIKGRPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Three-spined-stickleback      QPADAERALDTMNFDVIKGRPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Ninespine-stickleback         QPADAERALDTMNFDVIKGRPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Wolf-eel                      QPADAERALDTMNFDVIKGRPVRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Tanaka's-snailfish            QPADAERALDTMNFDVIKGRPLRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
Lumpsucker                    QPADAERALDTMNFDVIKGRPLRIMWSQRDPSLRKSGVGNIFIKNLDKSIDNKALYDTFS
                              **.****************.*:**************************************

Human                         AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Honeycomb-rockfish            AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Pinecone-soldierfish          AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Channel-bull-blenny           AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Three-spined-stickleback      AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Ninespine-stickleback         AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Wolf-eel                      AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Tanaka's-snailfish            AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
Lumpsucker                    AFGNILSCKVVCDENGSKGYGFVHFETQEAAERAIEKMNGMLLNDRKVFVGRFKSRKERE
                              ************************************************************

Human                         AELGARAKEFTNVYIKNFGEDMDDERLKDLFGKFGPALSVKVMTDESGKSKGFGFVSFER
Honeycomb-rockfish            AELGARAKEFTNVYVKNFGEDMDEEKLRDVFSKYGNSMSIRVMTDDTGKSRGFGFVSFER
Pinecone-soldierfish          AELGARAKEFTNVYIKNFGEDMDDEKLREVFSKYGNAMSIRVMTDDSGKSRGFGFVSFER
Channel-bull-blenny           AELGARAKEFTNVYVKNFGEDMDEEKLRDVFSKYGNAMSIRVMTDDSGKSRGFGFVSFDR
Three-spined-stickleback      AELGARAKEFTNVYVKNFGEDMDEEKLRDVFSKYGNAMSIRVMSDDGGKSRGFGFVSFER
Ninespine-stickleback         AELGARAKEFTNVYVKNFGEDMDEEKLRDVFSKYGNAMSIRVMSDDGGKSRGFGFVSFER
Wolf-eel                      AELGARAKEFTNVYVKNFGEDIDEEKLRDVFSKYGNAMSIRVMSDDGGKSRGFGFVSFER
Tanaka's-snailfish            AELGARAKEFTNVYVKNFGEDMDEEKLRDVFSKFGNAMSIRVMSDDGGKSRGFGFVSFER
Lumpsucker                    AELGARAKEFTNVYVKNFGEDMDEEKLRDVFSKFGNAMSIRVMSDDGGKSRGFGFVSFER
                              **************:******:*:*.*.::*.*:* ::*:.**:*: ***.*******:*

Human                         HEDAQKAVDEMNGKELNGKQIYVGRAQKKVERQTELKRKFEQMKQDRITRYQGVNLYVKN
Honeycomb-rockfish            HEDAQKAVDEMNGKEYNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Pinecone-soldierfish          HEDAQKAVDEMNGKELNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Channel-bull-blenny           HEDAQKAVDEMNGKEFNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Three-spined-stickleback      HEDAQKAVDDLNGKEFNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Ninespine-stickleback         HEDAQKAVDDLNGKEFNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Wolf-eel                      HEDAQKAVDELNGKEFNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Tanaka's-snailfish            HEDAQKAVDELNGKEFNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
Lumpsucker                    HEDAQKAVDELNGKEFNGKLIYVGRAQKKVERQTELKRKFEQMKQDRMTRYQGVNLYVKN
                              *********::**** *** ***************************:************

Human                         LDDGIDDERLRKEFSPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Honeycomb-rockfish            LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Pinecone-soldierfish          LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Channel-bull-blenny           LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Three-spined-stickleback      LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Ninespine-stickleback         LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Wolf-eel                      LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Tanaka's-snailfish            LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
Lumpsucker                    LDDGIDDERLRKEFTPFGTITSAKVMMEGGRSKGFGFVCFSSPEEATKAVTEMNGRIVAT
                              **************:*********************************************

Human                         KPLYVALAQRKEERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQTQNRA
Honeycomb-rockfish            KPLYVALAQRKEERQAHLTNQYMQRMATVRAVPNPVINPYQPAPPSGYFMAAIPPAQNRA
Pinecone-soldierfish          KPLYVALAQRKEERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQAQNRA
Channel-bull-blenny           KPLYVALAQRKEERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQTQNRA
Three-spined-stickleback      KPLYVALAQRKEERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQAQNRA
Ninespine-stickleback         KPLYVALAQRKEERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQAQNRA
Wolf-eel                      KPLYVALAQRKEERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQAQNRA
Tanaka's-snailfish            KPLYVALAQRKDERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQAQNR-
Lumpsucker                    KPLYVALAQRKDERQAHLTNQYMQRMASVRAVPNPVINPYQPAPPSGYFMAAIPQAQNRA
                              ***********:***************:************************** :*** 

Human                         AYYPPS-QIAQLRPSPRWTAQGARPHPFQNMPGAIRPAAPRPP-FSTMRPASSQVPRVMS
Honeycomb-rockfish            AYYPAAGQMAQLRPSPRWATQGVRPQHFQNMPGVMRPSAPRPQTFGAMRPT-GQMPRMMS
Pinecone-soldierfish          AYYPAAGQMAQLRPSPRWATQGVRPQHFQNMPGAMRPSAPRPQTFSTMRPA-SQVPRMMS
Channel-bull-blenny           AYYPAAGQMAQIRPSPRWATQGVRPQHFQNMPGAMRPSAPRPQTFGAMRPT-SQVPRMMS
Three-spined-stickleback      AYYQAAGQMAQLRPSPRWATQGVRPQHFQNMPGAMRPSAPRPQTFGAMRPP-AQVPRMMS
Ninespine-stickleback         AYYQAAGQMAQLRPSPRWATQGVRPQHFQNMPGAMRPSAPRPQSFGAMRPP-SQVPRMMS
Wolf-eel                      AYYQAAGQMAQLRPSPRWATQGVRPQHFQNMPGAMRPSAPRPQTFGTMRPT-SQVPRMMS
Tanaka's-snailfish            AYYQAAGQMAQLRPSPRWATQGVRPQQFQNMPGAMRPSAPRPQTFGAMRPT-SQVPRMMS
Lumpsucker                    AYYQAAGQMAQLRPSPRWATQGVRPQHFQNMPGAMRPSAPRPQTFGAMRPA-SQVPRMMS
                              *** .: *:**:******::**.**: ******.:**:****  *.:***. .*:**:**

Human                         TQRVANTSTQTMGPRPAAAAAAATPAVRTVPQYKYAAGVRNPQQHLNAQPQVTMQQPAVH
Honeycomb-rockfish            AQRVAG---QPMGPRPAMAAAAAAAPVRGVPQYKYAAGVRNPQQHMPVQPQVPMQQPAVH
Pinecone-soldierfish          TQRVA----QTMGPRPTTAAAAAAPPVRGVPQYKYAAGVRNPQQHITTQPQVTMQQPAVH
Channel-bull-blenny           AQRVA----QTMGPRPANPAAAAAAPVRGVPQYKYAAGVRNPQQHMPAQ-QVPMQQPAVH
Three-spined-stickleback      AQRVA----QSMGPRPAAAATVA--PVRGVPQYKYAAGVRNPQQHMPAQP-VPMQQPAVH
Ninespine-stickleback         AQRVG----QSMGPRPAAAAAVA--PVRGVPQYKYAAGVRNPQQHMPTQPQVPMQQPAVH
Wolf-eel                      TQRVA----QTMGPRPAVAAAAAGVPVRGVPQYKYAAGVRNPQQHIPAQPQVPMQQPAVH
Tanaka's-snailfish            AQRVA----QPMGPRPASAAAAA--PVRGVPQYKYATGVRNPQQHIPAQPQVPMQQPAVH
Lumpsucker                    AQRVA----QTMGPRPASAAAAA--PVRGVPQYKYATGVRNPQQHIPAQPQVPMQQPAVH
                              :***.    *.*****: .*:.*  .** *******:********: .*  *.*******

Human                         VQGQEPLTASMLASAPPQEQKQMLGERLFPLIQAMHPTLAGKITGMLLEIDNSELLHMLE
Honeycomb-rockfish            VQGQEPLTTTMLTAAPPQEQKQMLGERLFPLIQGMHPSLAGKITGMLLEIDNSELLHMLE
Pinecone-soldierfish          VQGQEPLTASMLAAAPPQEQKQMLGERLFPLIQNMHPSLAGKITGMLLEIDNSELLHMLE
Channel-bull-blenny           VQGQEPLTASMLAAAPPQEQKQMLGERLFPLIQNMHPSLAGKITGMLLEIDNSELLHMLE
Three-spined-stickleback      VQGQEPLTASMLAAAPPQEQKQMLGERLFPLIQNMHPSLTGKITGMLLEIDNSELLHMLE
Ninespine-stickleback         VQGQEPLTASMLAAAPPQEQKQMLGERLFPLIQNMHPSLTGKITGMLLEIDNSELLHMLE
Wolf-eel                      VQGQEPLTASMLAAAPPQEQKQMLGERLFPLIQNMHPSLTGKITGMLLEIDNSELLHMLE
Tanaka's-snailfish            VQGQEPLTASMLAAALPQEQKQMLGERLFPLIQNMHPSLTGKITGMLLEIDNSELLHMLE
Lumpsucker                    VQGQEPLTASMLAAALPQEQKQMLGERLFPLIQNMHPALTGKITGMLLEIDNSELLHMLE
                              ********::**::* ***************** ***:*:********************

Human                         SPESLRSKVDEAVAVLQAHQAKEAAQKAVNSATGVPTV
Honeycomb-rockfish            SPESLRSKVEEAVAVLQAHQAKEAAQKPVPNAAAVPSV
Pinecone-soldierfish          SPESLRSKVDEAVAVLQAHQAKEAAQKTVTNSTGVPSV
Channel-bull-blenny           SPESLRSKVDEAVAVLQAHQAKENSQKTVTNPAGVPSV
Three-spined-stickleback      SPESLRSKVDEAVAVLQAHQAKETAQKTVTNSAGVQSV
Ninespine-stickleback         SPESLRSKVDEAVAVLQAHQAKETAQKTVTNSAGVQSV
Wolf-eel                      SPESLRSKVDEAVAVLQAHQAKEAVQKTVTNSAGVPSV
Tanaka's-snailfish            SPESLRSKVDEAVAVLQAHQAKEATQKPVTNSAGVPSV
Lumpsucker                    SPESLRSKVDEAVAVLQAHQAKEATQKPVTNSAGIPSV
                              *********:*************  **.* ..:.: :*
